### ISSUE TITLE
TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by eremeyko** [Dionis1902/AccountGeneratorHelper#2]
**Describe the bug**
All mail-generator returns TypeError: 'type' object is not subscriptable

**To Reproduce**
1. `pip install account-generator-helper`
2. Copy the example: https://github.com/DioniS1902/AccountGeneratorHelper/blob/main/examples/temp_mail/gmailnator.py
3. Insert it into the IDE and run
4. Get the Traceback

**Expected behavior**
Normal, expected by comments, script operation 

**Screenshots**
![image](https://user-images.githubusercontent.com/60701195/162576544-00761639-ed7f-430f-8d5d-59803afec480.png)

**Desktop (please complete the following information):**
 - OS: win7, 7601 SP1
 - Python ver 3.8.9
- VS code: v. 1.64.4 | Electron: 13.5.2 | Chromium: 91.0.4472.164 | Node.js: 14.16.0| V8: 9.1.269.39-electron.0 | ОС: Windows_NT ia32 6.1.7601
- Powershell 2009

**Comment by Dionis1902** [comment]
Fixed
Please update the library

**Comment by eremeyko** [comment]
New error
![image](https://user-images.githubusercontent.com/60701195/163408281-2c1eb939-f384-445e-972f-96c0205a71ff.png)
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\User\AppData\Local\Programs\Python\Python38-32\lib\site-packages\account_generator_helper\__init__.py", line 1, in <module>
    from .temp_mail import *
  File "C:\Users\User\AppData\Local\Programs\Python\Python38-32\lib\site-packages\account_generator_helper\temp_mail\__init__.py", line 1, in <module>
    from .inboxkitten import InboxKitten
  File "C:\Users\User\AppData\Local\Programs\Python\Python38-32\lib\site-packages\account_generator_helper\temp_mail\inboxkitten\__init__.py", line 2, in <module>
    from .letter import Letter
  File "C:\Users\User\AppData\Local\Programs\Python\Python38-32\lib\site-packages\account_generator_helper\temp_mail\inboxkitten\letter.py", line 3, in <module>
    from ..mail import letter
  File "C:\Users\User\AppData\Local\Programs\Python\Python38-32\lib\site-packages\account_generator_helper\temp_mail\mail\__init__.py", line 7, in <module>
    class Mail:
  File "C:\Users\User\AppData\Local\Programs\Python\Python38-32\lib\site-packages\account_generator_helper\temp_mail\mail\__init__.py", line 34, in Mail
    def get_inbox(self) -> list[Letter]:
TypeError: 'type' object is not subscriptable`

**Comment by Dionis1902** [comment]
Now exactly fixed

**Comment by eremeyko** [comment]
All works, starred <3
